// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKKlItgQmxS6eCGDWI5z2_p6XttznTOY',
    appId: '1:886749946894:web:3495961306e2956129085f',
    messagingSenderId: '886749946894',
    projectId: 'test-firebase-e2d3c',
    authDomain: 'test-firebase-e2d3c.firebaseapp.com',
    storageBucket: 'test-firebase-e2d3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx83f0QJ-aoB9KCMxSREkr_c5aDVO0yjQ',
    appId: '1:886749946894:android:f9be760423f8b60c29085f',
    messagingSenderId: '886749946894',
    projectId: 'test-firebase-e2d3c',
    storageBucket: 'test-firebase-e2d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6X_VGHHRB3mulufT_BXdJHbqXlpyAmQ',
    appId: '1:886749946894:ios:cebe0e0ef745bc8029085f',
    messagingSenderId: '886749946894',
    projectId: 'test-firebase-e2d3c',
    storageBucket: 'test-firebase-e2d3c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD6X_VGHHRB3mulufT_BXdJHbqXlpyAmQ',
    appId: '1:886749946894:ios:cebe0e0ef745bc8029085f',
    messagingSenderId: '886749946894',
    projectId: 'test-firebase-e2d3c',
    storageBucket: 'test-firebase-e2d3c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLKKlItgQmxS6eCGDWI5z2_p6XttznTOY',
    appId: '1:886749946894:web:3e5723e2d1e13a1b29085f',
    messagingSenderId: '886749946894',
    projectId: 'test-firebase-e2d3c',
    authDomain: 'test-firebase-e2d3c.firebaseapp.com',
    storageBucket: 'test-firebase-e2d3c.firebasestorage.app',
  );
}
